-- CreateEnum
CREATE TYPE "BookingType" AS ENUM ('NEW_SUBSCRIPTION', 'RENEW_SUBSCRIPTION', 'EXTEND_SUBSCRIPTION', 'MEETING_ROOM');

-- AlterTable
ALTER TABLE "Booking" ADD COLUMN     "bookingType" "BookingType" NOT NULL DEFAULT 'NEW_SUBSCRIPTION';
